name: Claude Code

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Prompt for Claude'
        required: true
        type: string

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@v1
        with:
          prompt: ${{ inputs.prompt }}
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}